name: geofence_tracker
description: "Track locations with geofence alerts"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get: ^4.7.2
  logger: ^2.5.0
  fluttertoast: ^8.2.12
  flutter_local_notifications: ^19.2.0
  flutter_background_service: ^5.1.0
  google_maps_flutter: ^2.12.1
  geolocator: ^9.0.2
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true
  web: false

  android_gravity: center
  ios_content_mode: center

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#ffffff"



flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/


  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/font/ProximaNova-Regular.otf




